from __future__ import annotations

from typing import Any, Protocol, Sequence

from .boundary import AuthorizedEffect
from .contracts import ActionEnvelope, AuthorityDecision, LearningEvent


class SemanticMemoryPort(Protocol):
    def remember(self, event: LearningEvent) -> str: ...
    def recall(self, query: str) -> Sequence[dict[str, Any]]: ...


class DurableGraphPort(Protocol):
    def upsert_learning_event(self, event: LearningEvent) -> str: ...
    def related_context(self, failure_signature: str) -> Sequence[dict[str, Any]]: ...


class LiveStatePort(Protocol):
    def load_snapshot(self, snapshot: dict[str, Any]) -> str: ...
    def query(self, statement: str) -> Sequence[dict[str, Any]]: ...


class SandboxPort(Protocol):
    def checkout(self, repository: str, base_sha: str) -> str: ...
    def run(self, command: str) -> dict[str, Any]: ...
    def diff(self) -> str: ...


class SecurityScannerPort(Protocol):
    def scan(self, workspace: str) -> dict[str, Any]: ...


class MuscleMemoryPort(Protocol):
    def capture(self, event: LearningEvent) -> str: ...
    def replay(self, play_id: str, fresh_inputs: dict[str, Any]) -> dict[str, Any]: ...


class AuthorityPort(Protocol):
    def evaluate(self, action: ActionEnvelope) -> AuthorityDecision: ...


class EffectPort(Protocol):
    def execute(self, authorized: AuthorizedEffect) -> dict[str, Any]: ...
